spring:
  application:
    name: three-panthers
  
  datasource:
    url: jdbc:postgresql://ep-quiet-sun-ao6do42h-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_Bsp5fXYyNx2t
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      max-lifetime: 180000
      keepalive-time: 60000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntngocmailgl@gmail.com 
    password: gzvp wckm mhro qypp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
server:
  port: 8080
